name = "rotartsilib"
version = "0.1.0"
defaultTargets = ["app1", "app2", "build_slides"]


[[require]]
name = "doc-gen4"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso.git"
rev = "main"

[[require]]
name = "subverso"
git = "https://github.com/leanprover/subverso.git"
rev = "main"

[[require]]
name = "verso-slides"
git = "https://github.com/leanprover/verso-slides.git"
rev = "main"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Rotartsilib"


[[lean_exe]]
name = "app1"
root = "Executables.App1.Main"

[[lean_exe]]
name = "app2"
root = "Executables.App2.Main"

[[lean_lib]]
name = "VersoContent"
requiresModuleSystem = true

[[lean_exe]]
name = "build_slides"
root = "VersoContent.SlidesMain"
